### ISSUE TITLE
The kubectl commands become significant slower when using kubelogin

### ISSUE THREAD

**Issue by JiayangZhou** [Azure/kubelogin#102]
In AKS, we started to get warnings such as below:
![image](https://user-images.githubusercontent.com/47085823/178996615-32899a92-9aab-484d-881c-92adb65892ce.png)

So we adopted kubelogin by running the below commands: `kubelogin convert-kubeconfig -l azurecli`, which is non-interactively login to AKS. And then every time we run a kubectl command, we can feel a delayed response time. The issue is gone if do the normal way of refreshing AKS token via `az aks get-credentials`.

The kubeconfig file looks something like this when the issue is present:

```
- name: clusterUser_clustername
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - get-token
      - --server-id
      - XXXXX
      - --login
      - azurecli
      command: kubelogin
      env: null
      provideClusterInfo: false
```

This has been reported by many of our developers, but everybody uses the same AKS cluster, we will also initiate an Azure support ticket and see if it has something to do on cluster level, and also try in different clusters. But feel this is more related to kubelogin.
