### ISSUE TITLE
--token-cache-dir broken in kubelogin-linux-amd64

### ISSUE THREAD

**Issue by kubermihe** [Azure/kubelogin#108]
Hi,

we use kubelogin to connect to our on-premise kubernetes cluster, like it's described on https://github.com/Azure/kubelogin#setup-for-kubernetes-oidc-provider-using-azure-ad . It works very well and authentication works.

After successful authentication, the .json-file is saved in the working-directory, where i'm located during the login process and not in `~/.kube/cache/kubelogin`. When i now change the directory in my shell, the login has to be done again. This problem exists, wheter the parameter `--token-cache-dir` is set in `~/.kube/config` the parameter or not. As far as i understand, default for `--token-cache-dir` is always `~/.kube/cache/kubelogin`, so it's not important to set it in our case.

Here's the users-part from my `~/.kube/config`:
```
users:
- name: azure-user
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - get-token
      - --login
      - devicecode
      - --server-id
      - $AAD_CLIENT_ID
      - --token-cache-dir
      - ~/.kube/cache/kubelogin
      - --client-id
      - $AAD_CLIENT_ID
      - --tenant-id
      - $AAD_TENANT_ID
      - --environment
      - AzurePublicCloud
      command: kubelogin
      env: null
      provideClusterInfo: false
```
If i try to revoke the token with `kubelogin remove-tokens`, the token is not deleted from the working-directory it was created. When i move the .json file to `~/.kube/cache/kubelogin` directory and re-execute the revoke-command, the token has been deleted.

This scenario is with kubelogin-linux-amd64 (v0.0.16) in Ubuntu-20.04 WSL on Windows 11. I expect to have a valid token, no matter in which directory i'm at the moment. Is this a bug or do we have to set another setting? Does it not work because of the parameter order in the `~/.kube/config`?

Thanks.
