### ISSUE TITLE
Kubelogin converted k8s configs drops AzurePublicCloud-*.json files containing my token in current dir

### ISSUE THREAD

**Issue by WilliamDahlen** [Azure/kubelogin#121]
Hi, 

Ive encountered a wierd problem. I don't know if it is kubelogin who is the culprit. It might aswell be az-cli or kubectl itself, but ill start here.

When running kubectl commands anywhere on my system the combination of kubectl, kubelogin and az-cli creates a file in the current directory containing my azure token in the following format:

Filename: AzurePublicCloud-<longstring>--.json

```json
{
    "access_token":"",
    "refresh_token":"",
    "expires_in":0,
    "expires_on":12345678,
    "not_before":0,
    "resource":"",
    "token_type":""
}
```

If i move to new directory and run `kubectl` again, a new file just like the one in the other directory is created here aswell.

You can reproduce the issue the following way:

Versions:
```
kubectl: v1.24.3

kubelogin version 
git hash: v0.0.16/b61a6ef2b83d81e57b5ecc15d384b9da367f365e
Go version: go1.17.12
Build time: 2022-07-18T20:29:13Z

azure-cli                         2.38.0 *
core                              2.38.0 *
telemetry                          1.0.6 *
Extensions:
ssh                                1.0.1
Dependencies:
msal                            1.18.0b1
azure-mgmt-resource             21.1.0b1
```

Get fresh kubeconfigs from azure using az cli
`az aks get-credentials --name <k8sname> --resource-group <rg> --subscription <sub> --file newconfig`

Convert them with kubelogin
`kubelogin convert-kubeconfig -l azurecli --kubeconfig newconfig`

The users section in my newconfig file lookes like this after converting.
```yaml
users:
- name: clusterUser_rg-clustername
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - get-token
      - --login
      - azurecli
      - --server-id
      - <server uuid>
      command: kubelogin
      env: null
      interactiveMode: IfAvailable
      provideClusterInfo: false

```

Login to az-cli to get authenticated
`az login --use-device-code`

You should now have a file named "AzurePublicCloud-<longstring>--.json" in the current directory. Try to move to a new dir and run kubectl again.

Please let me know if i am doing anything to cause this myself.
