### ISSUE TITLE
You must be logged in to the server (Unauthorized)

### ISSUE THREAD

**Issue by tao-zhang-shell** [Azure/kubelogin#136]
SPN and certificate are used with kubelogin. Here is the kubeconfig after kubelogin exec plugin executed:

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: XXXXXX
    server: https://XXXXXX.hcp.westeurope.azmk8s.io:443
  name: default
contexts:
- context:
    cluster: default
    user: default
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: default
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - get-token
      - --login
      - spn
      - --server-id
      - 6dae42f8-4368-4678-94ff-3960e28e3630
      - --client-id
      - XXXXXXXX
      - --tenant-id
      - XXXXXXXX
      - --environment
      - AzurePublicCloud
      - --client-certificate
      - /path/to.pfx
      command: kubelogin
      env: null

```

If I run any kubectl command, it gives me error '**You must be logged in to the server (Unauthorized)**'.

The strange thing is, if I run **kubelogin get-token** locally with the same arguments, I'm able to get the token.

A cluster role binding is already created in the cluster, and object id of this SPN is used in role binding.
