### ISSUE TITLE
AKS upgrade to 1.24.6 - Terraform provider issue

### ISSUE THREAD

**Issue by extravio** [Azure/kubelogin#143]
We're deploying app to AKS through azure pipelines and Terraform.
Everything was working well on AKS 1.23 (**with local accounts disabled** )

The following tasks are executed in the pipeline to authenticate using az cli + kubelogin convert-kubeconfig -l azurecli 

```yml
- bash: |
        latesttag=$(curl -s https://api.github.com/repos/Azure/kubelogin/releases/latest | jq ".. .tag_name? // empty" | tr -d \")
        curl -LO "https://github.com/Azure/kubelogin/releases/download/$latesttag/kubelogin-linux-amd64.zip"
        unzip -j "kubelogin-linux-amd64.zip" -d $(Agent.TempDirectory)
        chmod +x $(Agent.TempDirectory)/kubelogin
        $(Agent.TempDirectory)/kubelogin --version
      displayName: Kubelogin - Install
- task: AzureCLI@2
   displayName: Kubelogin - Auth
   inputs:
        azureSubscription: ${{ variables.azureServiceConnection }}
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          export PATH=$(Agent.TempDirectory):$PATH
          az login --service-principal --username "${{ variables.ServicePrincipalAppId }}" --password "$(ServicePrincipalKubeLoginToken)" --tenant "${{ variables.AzureTenantId }}" 
          az aks get-credentials -g ${{ variables.azureResourceGroup }} -n ${{ variables.k8sClusterName }} && kubelogin convert-kubeconfig -l azurecli --tenant-id "${{ variables.AzureTenantId }}" 
```

The Terraform provider is configured as below: 
(the AKS cluster is defined as a data source)

```tf
provider "kubernetes" {
  host                   = data.azurerm_kubernetes_cluster.default.kube_config.0.host
  cluster_ca_certificate = base64decode(data.azurerm_kubernetes_cluster.default.kube_config.0.cluster_ca_certificate)
  exec {
    api_version = "client.authentication.k8s.io/v1beta1"
    command     = "/azp/agent/_work/_temp/kubelogin"
    args = [
      "get-token",
      "--login",
      "spn",
      "--environment",
      "AzurePublicCloud",
      "--tenant-id",
      data.azurerm_subscription.current.tenant_id,
      "--server-id",
      var.aad_server_id,
      "--client-id",
      var.sp_app_id,
      "--client-secret",
      var.sp_token
    ]
  }
}
```

After upgrading to AKS 1.24.6, the Terraform plan gives this error:

```sh
│ Error: Invalid index
│ 
│   on provider.tf line 24, in provider "kubernetes":
│   24:   host                   = data.azurerm_kubernetes_cluster.default.kube_config.0.host
│ 
│ The given key does not identify an element in this collection value.

```

Is there anything I need to modify in the bash script for kube_config to work again?
