### ISSUE TITLE
Support converting between different exec login methods

### ISSUE THREAD

**Issue by karthikbalasub** [Azure/kubelogin#193]
The behavior of `az aks get-credentials` changed to return `exec` format config with `devicecode` (interactive) mode by default now. Eg,
```
name: test-cluster
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - get-token
      - --environment
      - AzurePublicCloud
      - --server-id
      - <redacted>
      - --client-id
      - <redacted>
      - --tenant-id
      - <redacted>
      - --login
      - devicecode
      command: kubelogin
      env: null
      provideClusterInfo: false
```
This prevents kubelogin to convert it to non interactive mode (eg `spn`) as it currently only converts `azure` format configs. 

What needs to  be supported?
 `kubelogin` should add an option to convert `exec` format configs from one login method to another. 
new option: `-f  --from  Current login method to convert from`

 For example,

`kubelogin convert-kubeconfig -l spn -f devicecode`
