### ISSUE TITLE
Empty client secret when defining it from environment variables

### ISSUE THREAD

**Issue by alk-adong** [Azure/kubelogin#196]
Hello,

We are using a service principal with kubelogin and recently migrated to the following commandline:

```
# Before
kubelogin convert-kubeconfig --login spn --client-id ${ARM_CLIENT_ID} --client-secret ${ARM_CLIENT_SECRET}

# After
kubelogin convert-kubeconfig --login spn --use-azurerm-env-vars
```

However, with the new commandline, in the `~/.kube/config` file, we are missing the `--client-secret` argument and its value.

```
- name: clusterUser_REDACTED
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - get-token
      - --login
      - spn
      - --server-id
      - REDACTED
      - --client-id
      - REDACTED
      - --tenant-id
      - REDACTED
      - --environment
      - AzurePublicCloud
      command: kubelogin
      env: null
      provideClusterInfo: false
```

It results in the following error:

```
Error: both clientSecret and clientcert cannot be empty
```

I noticed that changing to the following commandline fixes the issue:

```
kubelogin convert-kubeconfig --login spn --use-azurerm-env-vars --client-secret ""
```

Most likely, this is the responsible part, as it checks that the flag is defined in the commandline arguments instead of checking if the value in the struct is non-empty.

https://github.com/Azure/kubelogin/blob/992e74d0fdb4426b36d49a0486be68b9f230d487/pkg/converter/convert.go#L251-L261
