### ISSUE TITLE
kubelogin is incompatible with Azure OIDC in GitHub Actions

### ISSUE THREAD

**Issue by rtsisyk** [Azure/kubelogin#239]
az-test.yaml
```
name: Az login test

on:
  workflow_dispatch: {}
  push:
    branches:
      - az_workflow_test

permissions:
  id-token: write
  contents: read

jobs:
  test:
    name: testing
    environment: dev
    runs-on:
      - self-hosted
      - linux
      - X64
      - gcp
      - dev
    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      - name: refresh token
        run: |
          set -ex
          az aks get-credentials --resource-group platforms-1 --name platforms-1 --context az-test
          cat /root/.kube/config
          while true; do
            echo '--------------'
            kubectl get nodes --context=az-test --kubeconfig=/root/.kube/config
            sleep 60
          done
```

```
az aks get-credentials --resource-group test-1 --name test-1 --context az-test
WARNING: Merged "az-test" as current context in /root/.kube/config
```

cat `/root/.kube/config`:
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: <REDACTED>
    server: <REDACTED>
  name: az-test
contexts:
- context:
    cluster: az-test
    user: clusterUser_test-1_test-1
  name: az-test
current-context: az-test
kind: Config
preferences: {}
users:
- name: clusterUser_test-1_test-1
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - get-token
      - --environment
      - AzurePublicCloud
      - --server-id
      - <REDACTED>
      - --client-id
      - <REDACTED>
      - --tenant-id
      - <REDACTED>
      - --login
      - devicecode  <!-- looks wrong
      command: kubelogin
      env: null
      provideClusterInfo: false
````

kubectl:
```
+ kubectl get nodes --context=az-test --kubeconfig=/root/.kube/config
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code <REDACTED> to authenticate.
```
