### ISSUE TITLE
Azure CLI not found on path error

### ISSUE THREAD

**Issue by michalanglart** [Azure/kubelogin#240]
Hello,

I have an issue with making `kubelogin` work properly.

Here is the fragment of my kubeconfig file:

```
user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - get-token
      - --login
      - azurecli
      - --server-id
      - <UUID cut out>
      command: kubelogin
      env: null
      provideClusterInfo: false
```

When I try to run any kubectl operation I'm getting "Azure CLI not found on path" error despite the fact that I do have `az` in path. Attaching screenshot with a session which shows that I can run the actual command which `kubelogin` is running (`az account get-access-token`). However when run via `kubelogin` it appears like if the env variable (`$PATH`) wouldn't be passed to child process.

![kubelogin](https://user-images.githubusercontent.com/14932410/229743116-5c6eea42-a535-4748-9dbe-2fe1333b6355.png)
