### ISSUE TITLE
Variable overrides parameter value inside kubeconfig

### ISSUE THREAD

**Issue by Skyere** [Azure/kubelogin#329]
Hello!
I noticed weird thing with the config
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: cert
    server: server
  name: name
contexts:
- context:
    cluster: cluster
    user: user
  name: name
current-context: context
kind: Config
preferences: {}
users:
- name: name
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - get-token
      - --login
      - spn
      - --server-id
      - serverid
      - --client-id
      - clientid
      - --tenant-id
      - tenantid
      - --environment
      - env
      - --client-secret
      - secret
      command: kubelogin
      env: null
      provideClusterInfo: false
 ```
`AZURE_CLIENT_ID` variable will be used instead of value clientid in the kubeconfig
