### ISSUE TITLE
weird authorization error when authenticating via service principal

### ISSUE THREAD

**Issue by DavidHe1127** [Azure/kubelogin#403]
I was following this [guide](https://azure.github.io/kubelogin/topics/sp.html) to authenticate against my cluster via service principal. So what I did was:

- Firstly register an app in EntraID
- Grant the app some permissions via RBAC
```yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ado-svc-role
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ado-svc-role-binding
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: <app_object_id>
roleRef:
  kind: ClusterRole
  name: ado-svc-role
  apiGroup: rbac.authorization.k8s.io
```
- Auth and verification

```sh
export AAD_SERVICE_PRINCIPAL_CLIENT_ID=<app-client-id>
export AAD_SERVICE_PRINCIPAL_CLIENT_SECRET=<app-secret-id>

az login --service-principal -u <app-client-id> -p <app-client-secret> --tenant <tenant-id>

az aks get-credentials --subscription <subscription-id> --resource-group <resource-group-name> --name <cluster-name> --file ./custom-kubeconfig

export KUBECONFIG=$(pwd)/custom-kubeconfig

kubelogin --kubeconfig "${KUBECONFIG}" convert-kubeconfig -l spn --client-id ${AAD_SERVICE_PRINCIPAL_CLIENT_ID} --client-secret ${AAD_SERVICE_PRINCIPAL_CLIENT_SECRET} \
    --tenant-id <tenant-id>

kubectl get nodes
```

## Expected Result

Command returns nodes information.

## Actual Result

`kubectl get nodes` command returns error below:

```
Error from server (Forbidden): nodes is forbidden: User "xxxx" cannot list resource "nodes" in API group "" at the cluster scope
```

## Comments

The user `xxxx` cannot be linked to the app I've used to login in any way - the uuid of the user (masked by xxxx) is unknown to me.
