### ISSUE TITLE
Azure AD v2 endpoints doesn't work

### ISSUE THREAD

**Issue by Jellyfrog** [Azure/kubelogin#411]
Hi,

I'm not sure this is due to kubelogin or a more generic kubernetes problem.
According to #317 it seems it should work tho?

When using the old v1 urls this works to auth and rolebind against groups etc,
but using the new v2 endpoints, the kubelogin command itself works and returns data, however api-server says:
`"Unable to authenticate the request" err="invalid bearer token"`

Using:
rke2 v1.29.0+rke2r1
kubelogin 0.1.0

Works:
```yaml
kube-apiserver-arg:
  - "oidc-issuer-url=https://sts.windows.net/<tenant id>/"
  - "oidc-client-id=<client id>"
  - "oidc-username-claim=upn"
  - "oidc-groups-claim=groups"
 ```

```yaml
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - get-token
      - --server-id
      - <client id>
      - --client-id
      - <client id>
      - --tenant-id
      - <tenant id>
      - --environment
      - AzurePublicCloud
      command: kubelogin
```

Doesn't work:
```yaml
kube-apiserver-arg:
  - "oidc-issuer-url=https://login.microsoftonline.com/<tenant id>/v2.0"
  - "oidc-client-id=<client id>"
  - "oidc-username-claim=upn" # also tried preferred_username from #317
  - "oidc-groups-claim=groups"
 ```

```yaml
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - get-token
      - --login 
      - interactive
      - --server-id
      - <client id>
      - --client-id
      - <client id>
      - --tenant-id
      - <tenant id>
      - --environment
      - AzurePublicCloud
      command: kubelogin
```

Any tips?
