### ISSUE TITLE
Token expires immediately

### ISSUE THREAD

**Issue by elia-zakeke** [Azure/kubelogin#424]
I'm using service principle authentication using get-token. The response contains a token that expires immediately. What can I do to make it last longer?

**Comment by weinong** [comment]
what do you mean by expiring immediately? did you paste the token to jwt.ms to look at expiry time?

**Comment by mikkel3000** [comment]
We have a similar issue where when using devicecode authentication with the --legacy option, we need to login on every kubectl command. When using level 5 logging, it seems that the kubelogin application never tries to cache credentials or retrieve credentials from cache.

Example kubeconfig:
```yaml
apiVersion: v1
kind: Config
clusters:
  - cluster:
      certificate-authority-data: something
      server: something
    name: test-cluster
contexts:
  - context:
      cluster: test-cluster
      namespace: default
      user: test-cluster
    name: test-cluster
current-context: test-cluster
preferences: {}
users:
  - name: test-cluster
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1beta1
        args:
            - -v
            - "5"
            - get-token
            - --login
            - devicecode
            - --server-id
            - something
            - --client-id
            - something
            - --tenant-id
            - something
            - --legacy
        command: kubelogin
        env: null
        installHint: |
            kubelogin is not installed which is required to connect to AAD enabled cluster.

            To learn more, please go to https://azure.github.io/kubelogin/
        provideClusterInfo: false

```
