### ISSUE TITLE
Proposal: kubeConfig contract for mandating PoP access tokens

### ISSUE THREAD

**Issue by manojampalam** [Azure/kubelogin#47]
Would like to propose the following contract in kubeConfig for a cluster that mandates access tokens with proof of posession (PoP) semantics. 

```yaml
kind: Config
preferences: {}
users:
- name: user-name
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      command: kubelogin
      args:
      - get-token
      - ...... specific auth flow parameters
      - --with-pop
      provideClusterInfo: true
```

##### --with-pop
To indicate that the returned token should be of type "pop" conforming to [SHR](https://tools.ietf.org/html/draft-ietf-oauth-signed-http-request-03>) format with API server's host name (conveyed via _provideClusterInfo_) captured as "u" claim.
