### ISSUE TITLE
Cluster RollBindings do not work w/ Service principal login flow (non interactive)

### ISSUE THREAD

**Issue by vanpyrzericj** [Azure/kubelogin#48]
I followed the instructions in the _Service principal login flow (non interactive)_ section, and I am able to successfully run `kubelogin convert-kubeconfig -l spn` and set the environmental variables as instructed. Upon trying to execute _any_ command such as `kubectl get no` or even `kubectl get namespace`, I receive the following error:

`Error from server (Forbidden): nodes is forbidden: User "<service-principal-object-id>" cannot list resource "nodes" in API group "" at the cluster scope`

I created the ClusterRoleBinding as instructed in the readme, and, when I login to `kubectl` interactively, I can confirm that the CRB is definitely in the cluster:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sp-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: <service-principal-object-id>
```

What am I missing here, that is preventing me from accessing the AKS cluster using non-interactive service principal?
