### ISSUE TITLE
kubelogin convert-kubeconfig -l spn prompts for interactive login

### ISSUE THREAD

**Issue by cvdsande** [Azure/kubelogin#49]
Maybe I'm not following the directions correctly, but I'm prompted for an interactive login when using
```
$ kubelogin convert-kubeconfig -l spn
$ kubectl get no
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code FN4N26MMT to authenticate.
```

Environment is set
```
$ env |grep AAD
AAD_SERVICE_PRINCIPAL_CLIENT_ID=foo
AAD_SERVICE_PRINCIPAL_CLIENT_SECRET=bar
```

Kubeconfig
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: <snip>
    server: <snip>
  name: aks-westus-test
contexts:
- context:
    cluster: aks-westus-test
    user: clusterUser_rg-aks-westus-test_aks-westus-test
  name: aks-westus-test
current-context: aks-westus-test
kind: Config
preferences: {}
users:
- name: clusterUser_rg-aks-westus-test_aks-westus-test
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - get-token
      - --environment
      - AzurePublicCloud
      - --server-id
      - <snip>
      - --client-id
      - <snip>
      - --tenant-id
      - <snip>
      command: kubelogin
      env: null
```

**Comment by weinong** [comment]
I guess when you run `kubelogin convert-kubeconfig -l spn` the `KUBECONFIG` env variable wasn't set.
your kubeconfig will need to look something like this
```yaml
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - get-token
      - --environment
      - AzurePublicCloud
      - --server-id
      - <snip>
      - --client-id
      - <snip>
      - --tenant-id
      - <snip>
      - --login
      - spn
      command: kubelogin
      env: null
```
