### ISSUE TITLE
Cached credentials are not checked when in legacy mode

### ISSUE THREAD

**Issue by danmx** [Azure/kubelogin#5]
After following kube config the [conversion script](https://github.com/Azure/kubelogin#device-code-flow-interactive) I have updated `kubeconfig`:

```yaml
user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - get-token
      - --environment
      - AzurePublicCloud
      - --server-id
      - xxx
      - --client-id
      - xxx
      - --tenant-id
      - xxx
      - --legacy
      command: kubelogin
      env: null
```

After running a kubectl command and confirming my identity I have credentials stored in `~/.kube/cache/kubelogin/azure.json`.
When I tried to run another kubectl command and it asked me to confirm my identity again.

I tried to not use `--legacy` and authenticate again and I got from k8s api server (obviously non-legacy type of credentials is not accepted):
```
error: You must be logged in to the server (the server has asked for the client to provide credentials)
```
When I tried to switch back to `--legacy` and still got the same error message.
The error disappeared when I cleared the cache and reauthenticated but I was back to having to authenticate every `kubectl` execution.
