### ISSUE TITLE
Kubectl authorization failing with timeout error in the Docker based Azure App Service

### ISSUE THREAD

**Issue by skythet** [Azure/kubelogin#52]
I'm using Docker based Azure App Service as a Azure Devops deployment agent for reaching our private network. In this app service enabled [Identity](https://docs.microsoft.com/en-us/azure/app-service/overview-managed-identity?tabs=dotnet#add-a-system-assigned-identity) and I want to use this identity for accessing AKS. 

In AKS granted ClusterAdmin role for this identity:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: <binding name>
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: <managed identity object id>
```

After configuration I tried to run deployment, but got next error:

```
W0209 12:49:50.510666    1246 transport.go:260] Unable to cancel request for *exec.roundTripper Error: failed to get token: adal: Failed to execute the refresh request. Error = 'Get http://169.254.169.254/metadata/identity/oauth2/token?api-version=2017-09-01&resource=<id>: dial tcp 169.254.169.254:80: i/o timeout' Unable to connect to the server: getting credentials: exec: executable kubelogin failed with exit code 1 (Client.Timeout exceeded while awaiting headers)
```

Kubelogin tries to get token from 169.254.169.254, but this endpoint works only under VM's, for App Services there is available "MSI_ENDPOINT" environment variable and kubelogin should use that endpoint. Also in the kubelogin this endpoint is hardcoded: https://github.com/Azure/kubelogin/blob/master/pkg/token/msi.go#L39

Continuing investigation I've found that  in a newer version of library adal `GetMSIVMEndpoint()` is deprecated and `NewServicePrincipalTokenFromMSI()` can automatically detect correct MSI endpoint: https://github.com/Azure/go-autorest/blob/master/autorest/adal/token.go#L714
