### ISSUE TITLE
Add argument for listening address or redirect uri

### ISSUE THREAD

**Issue by TazBruce** [Azure/kubelogin#606]
### Problem
At the moment, it is very difficult to authenticate via the interactive login mode within a docker container. (Device-code is not an allowed mode for our use case unfortunately.) Due to the fact that the redirect port is constantly changing, it is difficult to orchestrate a docker compose to expose the right port given that you need to know it in advance.

### Suggestion
Using some inspiration from [int128/kubelogin](https://github.com/int128/kubelogin/blob/master/docs/usage.md#authorization-code-flow), add the following argument to customise the authorisation flow:
- --listen-address=127.0.0.1:12345

**Comment by mwdomino** [comment]
I'm also very interested in this. I'd be happy to raise a PR myself if a maintainer could point me in the right direction as to where the change would be made.

Using my LSP I've landed in a bunch of interfaces in the `azidentity` package and got lost :)

**Comment by weinong** [comment]
https://github.com/Azure/kubelogin/pull/661

**Comment by weinong** [comment]
you can try it out at https://github.com/weinong/kubelogin/releases/tag/v0.2.8

**Comment by weinong** [comment]
@TazBruce I tried it in docker container. The interactive mode will kick off a browser which is unavailable in the container. How did you solve that?

**Comment by weinong** [comment]
@TazBruce I published that in my fork's release. you can download it manually to try it out. i plan to address other issues before I cut the new release here.
https://github.com/weinong/kubelogin/releases/tag/v0.2.8

**Comment by TazBruce** [comment]
Whoops my bad! Saw the docs were already updated and got excited 😆  I've had a go at pulling down your release and it appears that no matter the url I provide, the listening address always remains as localhost. Despite having 8181 exposed in my docker compose, no luck reaching it. To be able to reach an address from a docker compose, I believe the local address needs to be 0.0.0.0?

docker compose
```
services:
  dev:
    ports:
      - "127.0.0.1:8181:8181" # Port for kubelogin
```

kube config
```
- name: clusterUser_blah
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - get-token
      - --environment
      - xxx
      - --server-id
      - xxxx
      - --client-id
      - xxx
      - --tenant-id
      - xxxx
      - --redirect-url
      - http://0.0.0.0:8181
      - --login
      - interactive
      command: kubelogin
      env: null
      interactiveMode: IfAvailable
      provideClusterInfo: false
```

command
```
p941028@50d5ca1e5efd:/src$ kubectl get ns
Open url in browser: https://login.microsoftonline.com/xxxx/oauth2/v2.0/authorize?client_id=xxxx&code_challenge=xxxx&code_challenge_method=S256&prompt=select_account&redirect_uri=http%3A%2F%2Flocalhost%3A8181&response_type=code&scope=xxx&state=xxx
```

networking within container
```
netstat -ltp
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.11:39225        0.0.0.0:*               LISTEN      -
tcp        0      0 localhost:8181          0.0.0.0:*               LISTEN      1394/rosetta
```
