### ISSUE TITLE
Tokens obtained with devicecode + legacy are no longer cached

### ISSUE THREAD

**Issue by rombert** [Azure/kubelogin#640]
https://github.com/Azure/kubelogin/pull/608 has rewritten the way tokens are cached. As part of that `kubelogin get-token ... --legacy` no longer caches tokens.

This is a blocker for our adoption of newer kubelogin versions because obtaining new tokens on each kubectl invocation is way too slow for interactive use.

Are there plans to bring caching back for this kind of token?

**Comment by weinong** [comment]
we have been advised to stop handling token in insecure fashion. This is the breaking change we called out in new v0.2.0.

**Comment by weinong** [comment]
the alternative is to pin to v0.1.9

**Comment by rombert** [comment]
Thank you for the explanation. I will pin 0.1.9 for now

**Comment by jkugler** [comment]
> we have been advised to stop handling token in insecure fashion. This is the breaking change we called out in new v0.2.0.

Are you saying you'll never bring back caching? or that it will be a future feature? Caching in the OS'es secrets store seems like a good option. Windows, MacOS and Linux all have a secret store into which the tokens could be cached.

**Comment by jkugler** [comment]
Sorry, this is diverging from the ticket, but how do we know if we're using legacy? All I know is I'm getting login prompts trying to use k9s. :)

**Comment by weinong** [comment]
can you share the arguments used in the kubeconfig?

**Comment by jkugler** [comment]
Ah.
```
- name: adobe
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1
      args:
      - get-token
      - --server-id
      - 41abc0c6-712d-4619-9b79-b96da7ffa825
      - --client-id
      - 752c7d7f-e651-4ac3-939b-a049f390e19a
      - --tenant-id
      - fa7b1b5a-7b34-4387-94ae-d2c178decee1
      - --legacy
      command: kubelogin
      env: null
      interactiveMode: IfAvailable
      provideClusterInfo: false
```
