### ISSUE TITLE
Unable to authenticate the request due to an error: [invalid bearer token, oidc: verify token: failed to verify signature: failed to verify id token signature]

### ISSUE THREAD

**Issue by lknite** [Azure/kubelogin#74]
Hello, everything on the kubelogin side looks to be working perfectly.

Not having much luck with the above error which I am getting in the kube-apisever log.

I can see there is a parameter --oidc-ca-file which is probably what I need.  Where I am at we have security which rewrites SSL.  I have the ca-bundle for those, which had to be installed to worker nodes in order to successfully pull images.  I've tried the same ca-bundle via the --oidc-ca-file parameter without success.

Not sure how to resolve this.  Since many using kubelogin (azure version) may have also run into this, I thought this would be a good place to post the question as many may later on also come here and search for this error message.

Is there a certificate specific to azure's identity provider which I need to download, and configure via --oidc-ca-file?

**Comment by weinong** [comment]
are you using k8s oidc feature? did you look at https://github.com/Azure/kubelogin#setup-for-kubernetes-oidc-provider-using-azure-ad ?
tagging @markszabo since he has done something similar before

**Comment by lknite** [comment]
yes, that's what I'm doing

**Comment by lknite** [comment]
Installed kubelogin by unzipping a release and copying kubelogin to /usr/local/bin, also did a symlink to kubelogin called kubectl-oidc_login.

If I run kubelogin standalone it gets a token as expected:
```
kubelogin get-token ...
```

/etc/kubernetes/manifest/kube-apiserver.yaml
```
spec:
  containers:
  - command:
    - kube-apiserver
    - --oidc-groups-claim=groups
    - --oidc-ca-file=/etc/pki/tls/certs/ca-bundle.crt
    - --oidc-username-claim=upn
    - --oidc-client-id=e3<redacted>62
    - --oidc-issuer-url=https://sts.windows.net/c5<redacted>81/
```

.kube/config, modified current context
```
- context:
    cluster: 10.0.0.25
    namespace: demo
    user: azure-user
  name: dev
```
.kube/config, modified current context
```
users:
- name: azure-user
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - get-token
      - --environment
      - AzurePublicCloud
      - --server-id
      - e3<redacted>62
      - --client-id
      - e3<redacted>62
      - --client-secret
      - 7a<redacted>ZO
      - --tenant-id
      - c5<redacted>81
      command: kubelogin
      env: null
```

**Comment by lknite** [comment]
If I copy the token I'm getting back into jwt.io everything looks right except at the bottom, where it says Invalid Signature.  hmm

**Comment by markszabo** [comment]
Your error message seems to say that the API server failed to validate the signature. It gets the public key from `oidc-issuer-url=https://sts.windows.net/c5<redacted>81/` to do the verification, so maybe it can't get that key. I remember that some tools broke because `sts.windows.net` had an unexpected certificate chain (never figured out the details though). So could you try to `curl https://sts.windows.net/c5<redacted>81/v2.0/.well-known/openid-configuration` from a pod in the cluster? (To see if the https intercepting proxy can support it.) Also you can take the public key from the response and use it on jwt.io to verify the signature.

More about this endpoint [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-protocols-oidc) and an example response: https://sts.windows.net/common/v2.0/.well-known/openid-configuration

Another minor difference between my setup and what you described: I didn't use a client secret in the kubeconfig, and checked the `Allow public client flows` on the enterprise app. Not sure if this is related though.

**Comment by weinong** [comment]
> Another minor difference between my setup and what you described: I didn't use a client secret in the kubeconfig, and checked the Allow public client flows on the enterprise app. Not sure if this is related though.

+1

**Comment by lknite** [comment]
Thank you, via the well-known url I'm getting back that it is an invalid tenant.  Troubleshooting ...

**Comment by lknite** [comment]
The url does work from within a pod.  I put the url into a web browser and downloaded the public certificate, then appended the base64 encoded version to the ca file being passed to the kube-apiserver.  Restarted the kube-apiserver in case that was needed.  Still seeing the same error.

**Comment by weinong** [comment]
you don't need to download the certificates from AAD. Have you tried to configure your client app with Public Client App?

**Comment by lknite** [comment]
My coworker set up the client in azure.  I'm trusting they did so correctly but it would be OK to verify things are correct.  Since running kubelogin on its own gets a token, I figured it is setup correctly.

Sent with a Spark

**Comment by markszabo** [comment]
I don't think this changes anything, but there is an extra `/` at the end of your URL in `--oidc-issuer-url=https://sts.windows.net/c5<redacted>81/` compared to the [kubernetes docs](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#configuring-the-api-server).

After restarting the API server, could you check the logs for any message about calling this URL or obtaining the openID configuration?

**Comment by lknite** [comment]
The kube-apiserver log initially had an error about the '/' saying that the configured issuer didn't match the issuer in the token.  In the token the issuer does have a '/' so I went back to the api server and added the '/', afterwards the error went away and the new one in the original posting appeared.  ```[invalid bearer token, oidc: verify token: failed to verify signature: failed to verify id token signature]```

**Comment by lknite** [comment]
***
App Registrations

1. add new application
2. click 'authentication' at the left and click 'Allow public client flows', click 'Save'
3. click 'token configuration' at the left, click 'add groups claim', click 'Security groups'
   expand ID, Access, and SAML and click 'sAMAccountName' for each, click 'Add'
4. do not add a secret, kubernetes does not have an oid-client-secret option

***
Test using the (azure version) of kubelogin:
- verify groups are coming back using human readable values & are accurate to the user (via jwt.io)
- verify 'signature validated' (via jwt.io)

Note: Set the server-id to be the value of the client-id
```
kubelogin get-token \
      --environment \
      AzurePublicCloud \
      --server-id \
      0c<redacted>4c \
      --client-id \
      0c<redacted>4c \
      --tenant-id \
      c5<redacted>81
```
***
To configure kubernetes modify the kube-apiserver.yaml file adding:
```
    - --oidc-issuer-url=https://sts.windows.net/c5<redacted>81/
    - --oidc-client-id=0c<redacted>4c
    - --oidc-username-claim=upn
    - --oidc-groups-claim=groups
    - --oidc-ca-file=/etc/pki/tls/certs/ca-bundle.crt
```
***
To configure kubectl add to the kind section:
```
kind: Config
preferences: {}
users:
- name: azure-user
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - get-token
      - --environment
      - AzurePublicCloud
      - --server-id
      - 0c<redacted>4c
      - --client-id
      - 0c<redacted>4c
      - --tenant-id
      - c5<redacted>81
      command: kubelogin
      env: null
```
