### ISSUE TITLE
kubelogin may not work with MSI when run in Azure Container Instance

### ISSUE THREAD

**Issue by weinong** [Azure/kubelogin#79]
## Problem
Although `kubelogin` addresses https://github.com/kubernetes/kubernetes/issues/86410 to remove `spn:` prefix in `audience` claim, you may encounter the same issue while using `kubelogin` with Managed Service Identity (MSI) in Azure Container Instance (ACI).

For example
```sh
az login --identity --username ${MSI_CLIENT_ID}
kubelogin convert-kubeconfig -l azurecli
kubectl get pods
error: You must be logged in to the server (Unauthorized)

## If `guard` log is enabled in AKS control plane, you will see
## failed to verify token for azure: oidc: expected audience "6dae42f8-4368-4678-94ff-3960e28e3630" got ["spn:6dae42f8-4368-4678-94ff-3960e28e3630"]
```

The issue is in ACI where they have different infrastrucutres such that the returned MSI token on legacy one will include `spn:` prefix in `audience` claim. You can verify by examining the AAD token by `kubelogin get-token --server-id 6dae42f8-4368-4678-94ff-3960e28e3630 --client-id ${MSI_CLIENT_ID} --login msi` and paste the access token to https://jwt.ms and look at the `audience` claim. If it has `spn:`, your ACI is running on the legacy infrastructure.

## Mitigation
Please open support request to ACI team to migrate your subscription

## References
#30 #61

**Comment by djsly** [comment]
@weinong do you know if we still need to request a migration for our subs or this is now fixed for all subs ?

**Comment by va-chopra** [comment]
any fix on this?

**Comment by weinong** [comment]
Hi @va-chopra, I will need to check with ACI team. To be sure, are you still encountering the issue?

**Comment by va-chopra** [comment]
i was assigning the permissions to an msi so the following 2 commands in succession worked for me from inside the container

az aks get-credentials --resource-group $RG_NAME --name $AKS_CLUSTER_NAME --overwrite-existing
kubelogin convert-kubeconfig -l msi

**Comment by abhinovntap** [comment]
Hello @weinong and @va-chopra ,

We are trying to have kubelogin as a auth provider to another cluster using an MSI. If the AKS cluster's kubeconfig is programatically modified with authprovider object like shown below, would it work ?

````
users:
- name: <user-name>
  user:
    auth-provider:
      name: azure
      config:
        environment: AzurePublicCloud
        tenant-id: <azure-ad-tenant-id>
        client-id: <managed-identity-client-id>
        client-secret: <managed-identity-client-secret>

**Comment by weinong** [comment]
@abhinovntap , do you mean if this kubeconfig can be converted by kubelogin? or you want to use this kubeconfig as is? I am pretty sure it won't work as is. The legacy auth-provider: azure is removed from k8s long time ago. besides, it doesn't support msi, either. So if you want to use msi, you have to use kubelogin and your kubeconfig would look similar to below. That being said, use workload identity over msi.

```
- name: clusterUser_weinongw-test_aks-westus3
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - get-token
      - --login
      - azurecli
      - --server-id
      - 6dae42f8-4368-4678-94ff-3960e28e3630
      command: kubelogin
      env: null
      installHint: |2

        kubelogin is not installed which is required to connect to AAD enabled cluster.

        To learn more, please go to https://aka.ms/aks/kubelogin
      interactiveMode: IfAvailable
      provideClusterInfo: false
```
